name: Weekly ETL

on:
  schedule:
    - cron: "0 12 1 1 *"  # Runs every Wednesday and Friday at noon UTC
  workflow_dispatch:  

jobs:
  run-etl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.5'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download NLTK data
        run: |
          python -m nltk.downloader stopwords
          python -m nltk.downloader punkt

      - name: Ensure logs directory exists
        run: mkdir -p logs

      - name: Add secrets.ini file
        run: |
          mkdir -p config
          echo "[API_KEY]" > config/secrets.ini
          echo "x-rapidapi-key = ${{ secrets.X_RAPIDAPI_KEY }}" >> config/secrets.ini
          echo "x-rapidapi-host = ${{ secrets.X_RAPIDAPI_HOST }}" >> config/secrets.ini
          echo "[AWS_CREDENTIALS]" >> config/secrets.ini
          echo "ACCESS_KEY_ID = ${{ secrets.AWS_ACCESS_KEY_ID }}" >> config/secrets.ini
          echo "SECRET_ACCESS_KEY = ${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> config/secrets.ini

      - name: Run ETL script
        id: run-etl
        run: python scripts/etl/etl.py

      - name: Commit and push updated logs
        run: |
          git config --global user.name "Chidera Ozigbo"
          git config --global user.email "chideraozigbo@gmail.com"
          git add logs/etl_log.txt logs/processed_tweet_hashes.txt
          git commit -m "Update logs after ETL job"
          git push "https://${{ secrets.PAT_TOKEN }}@github.com/Chideraozigbo/sentiment-analysis-project.git" HEAD:main

  success-alert:
    runs-on: ubuntu-latest
    needs: run-etl
    if: success()
    steps:
      - name: Send success notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          subject: "ETL Job Success Notification"
          body: |
            The ETL job has completed successfully.

            Repository: ${{ github.repository }}
            Branch: ${{ github.ref_name }}
            Timestamp: $(date -u +'%Y-%m-%d %H:%M:%S UTC')

            This is an automated message. Please do not reply.
          to: 'chideraozigbo@gmail.com'
          from: Auto-Reports
          content_type: text/plain

  failure-alert:
    runs-on: ubuntu-latest
    needs: run-etl
    if: failure()
    steps:
      - name: Send failure alert
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          subject: "ETL Job Failure Notification"
          body: |
            The ETL job has failed.

            Repository: ${{ github.repository }}
            Branch: ${{ github.ref_name }}
            Timestamp: $(date -u +'%Y-%m-%d %H:%M:%S UTC')
            Failure Step: ${{ job.steps[0].name }}
            Commit Message: ${{ github.event.head_commit.message }}

            Please check the logs for more details.
          to: 'chideraozigbo@gmail.com, onubawinner042@gmail.com, honourdaniel987@gmail.com'
          from: Auto-Reports
          content_type: text/plain